name: cloud_garage
description: "A SaaS ERP System for SMEs Car Service Centers."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  equatable: ^2.0.7
  sqflite: ^2.4.1
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.0.0
  firebase_core: ^3.10.0
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    # Photos
    - assets/images/test_blue_gradient.png
    - assets/images/elKhawaga.png

    # Shapes
    - assets/shapes/side_wave.png
    - assets/shapes/yellow_wave.png
    - assets/shapes/purple_wave.png
    - assets/shapes/red_wave.png

    # Logos
    - assets/logos/saas_logo_64.png
    - assets/logos/saas_logo_256.png
    - assets/logos/saas_logo_512.png

  fonts:
    - family: TTHovesPro
      fonts:
        - asset: assets/fonts/TT Hoves Pro Trial Black.ttf
        - asset: assets/fonts/TT Hoves Pro Trial ExtraBold Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial ExtraLight.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Hairline Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Hairline.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Light.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Medium Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Medium.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Thin Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Thin.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Regular.ttf
        - asset: assets/fonts/TT Hoves Pro Trial ExtraBold.ttf
        - asset: assets/fonts/TT Hoves Pro Trial ExtraLight Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Light Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial DemiBold.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Bold.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Black Italic.ttf
        - asset: assets/fonts/TT Hoves Pro Trial Bold Italic.ttf

    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
